# Generated by Django 6.0.3 on 2026-03-24 15:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, help_text='User phone number for contact', max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pictures/')),
                ('date_of_birth', models.DateField(blank=True, help_text='User date of birth', null=True)),
                ('is_verified_email', models.BooleanField(default=False, help_text='Whether user has verified their email')),
                ('is_verified_phone', models.BooleanField(default=False, help_text='Whether user has verified their phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'custom_users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('sms_notifications_enabled', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('marketing_emails_enabled', models.BooleanField(default=True, help_text='Receive marketing emails and offers')),
                ('dark_mode_enabled', models.BooleanField(default=True, help_text='Use dark mode in frontend')),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], default='en', help_text='Preferred language', max_length=10)),
                ('currency', models.CharField(default='USD', help_text='Preferred currency for display', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User who owns these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping Address'), ('billing', 'Billing Address'), ('both', 'Both Shipping and Billing')], default='shipping', help_text='Type of address (shipping/billing)', max_length=20)),
                ('full_name', models.CharField(help_text='Full name for delivery', max_length=100)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('street_address', models.CharField(help_text='Street name and house number', max_length=255)),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('state_or_province', models.CharField(blank=True, help_text='State or province name', max_length=100, null=True)),
                ('postal_code', models.CharField(help_text='Postal/zip code', max_length=20)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('delivery_instructions', models.TextField(blank=True, help_text='Special instructions for delivery (e.g., leave package at door)', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
                'ordering': ['-is_default', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'address_type'), name='unique_default_address_per_type')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('purchase', 'Purchase'), ('review', 'Review Product'), ('wishlist_add', 'Add to Wishlist'), ('cart_add', 'Add to Cart'), ('password_change', 'Change Password'), ('profile_update', 'Update Profile')], help_text='Type of activity', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the activity', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser or device information', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who performed the activity', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='user_activi_user_id_6bb195_idx')],
            },
        ),
    ]
