# Generated by Django 6.0.3 on 2026-03-24 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('product_manager', 'Product Manager'), ('order_manager', 'Order Manager'), ('user_manager', 'User Manager'), ('payment_manager', 'Payment Manager')], help_text='Unique role identifier', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name for role', max_length=100)),
                ('permissions', models.TextField(help_text='Comma-separated list of permissions (view, add, edit, delete, etc.)')),
                ('description', models.TextField(blank=True, help_text='Description of this admin role', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role can be assigned to new admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
                'db_table': 'admin_roles',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_password_change', models.BooleanField(default=False, help_text='Admin must change password on next login')),
                ('last_admin_login', models.DateTimeField(blank=True, help_text='Last time admin logged into admin panel', null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last admin login', null=True)),
                ('is_active_admin', models.BooleanField(default=True, help_text='Whether admin can access admin panel')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Two-factor authentication for admin account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, help_text='Admin role and permissions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='users.adminrole')),
                ('user', models.OneToOneField(help_text='Link to CustomUser account', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'admin_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Admin Login'), ('logout', 'Admin Logout'), ('create_product', 'Create Product'), ('update_product', 'Update Product'), ('delete_product', 'Delete Product'), ('create_order', 'Create Order'), ('update_order_status', 'Update Order Status'), ('delete_order', 'Delete Order'), ('create_user', 'Create User'), ('update_user', 'Update User'), ('delete_user', 'Delete User'), ('update_settings', 'Update Settings'), ('manage_admin', 'Manage Admin Users'), ('other', 'Other Action')], help_text='Type of action performed', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of action')),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource affected (Product, Order, User, etc.)', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of resource affected', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which action was performed')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning')], default='success', help_text='Status of the action', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(help_text='Admin who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.adminuser')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'admin_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='admin_audit_created_5c232f_idx'), models.Index(fields=['admin_user', '-created_at'], name='admin_audit_admin_u_1f122d_idx'), models.Index(fields=['action'], name='admin_audit_action_d6f52c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of person submitting form', max_length=255)),
                ('email', models.EmailField(help_text='Email address for contact', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('subject', models.CharField(help_text='Subject of contact message', max_length=255)),
                ('message', models.TextField(help_text='Contact message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('responded', 'Responded'), ('archived', 'Archived')], default='new', help_text='Status of contact message', max_length=20)),
                ('response', models.TextField(blank=True, help_text='Admin response to contact message', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When admin responded to this message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_by', models.ForeignKey(blank=True, help_text='Admin who responded to this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_responses', to='users.adminuser')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contact_mes_created_684d0e_idx'), models.Index(fields=['status'], name='contact_mes_status_31d23b_idx'), models.Index(fields=['email'], name='contact_mes_email_a7fb56_idx')],
            },
        ),
    ]
