# Generated by Django 6.0.3 on 2026-03-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminrole_adminuser_adminauditlog_contactmessage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adminauditlog',
            name='admin_audit_created_5c232f_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminauditlog',
            name='admin_audit_admin_u_1f122d_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminauditlog',
            name='admin_audit_action_d6f52c_idx',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='contact_mes_created_684d0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='contact_mes_status_31d23b_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='contact_mes_email_a7fb56_idx',
        ),
        migrations.RemoveField(
            model_name='adminauditlog',
            name='admin_user',
        ),
        migrations.DeleteModel(
            name='AdminRole',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='responded_by',
        ),
        migrations.DeleteModel(
            name='AdminAuditLog',
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
