# Generated by Django 6.0.3 on 2026-03-24 15:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order number', max_length=100, unique=True)),
                ('shipping_address_data', models.JSONField(blank=True, default=dict, help_text='Backup shipping address data')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before tax/shipping', max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Shipping charges', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tax amount', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Discount/coupon amount', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Final total price', max_digits=10)),
                ('coupon_code', models.CharField(blank=True, help_text='Applied coupon/promotion code', max_length=100, null=True)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Current order status', max_length=20)),
                ('payment_method', models.CharField(choices=[('stripe', 'Credit/Debit Card (Stripe)'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('wallet', 'E-Wallet'), ('cod', 'Cash on Delivery')], help_text='Payment method used', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=200, null=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Special instructions from customer', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_delivery_date', models.DateField(blank=True, help_text='Estimated delivery date', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Actual delivery time', null=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name at time of order', max_length=200)),
                ('product_sku', models.CharField(help_text='Product SKU at time of order', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit when ordered', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total for this item', max_digits=10)),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('defective', 'Defective/Damaged'), ('wrong_item', 'Wrong Item Received'), ('not_as_described', 'Not as Described'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], help_text='Reason for return', max_length=50)),
                ('status', models.CharField(choices=[('requested', 'Return Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('refunded', 'Refunded')], default='requested', help_text='Return status', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount to be refunded', max_digits=10)),
                ('customer_comment', models.TextField(blank=True, help_text='Customer explanation', null=True)),
                ('admin_comment', models.TextField(blank=True, help_text='Admin notes', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_returns',
            },
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, help_text='Courier tracking number', max_length=100, null=True, unique=True)),
                ('courier', models.CharField(blank=True, help_text='Courier service name', max_length=100, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('picked', 'Picked'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed')], default='processing', help_text='Current shipment status', max_length=20)),
                ('status_updates', models.JSONField(blank=True, default=list, help_text='Array of status update events')),
                ('shipped_at', models.DateTimeField(blank=True, help_text='When package was shipped', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When package was delivered', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_shipments',
            },
        ),
    ]
