# Generated by Django 6.0.3 on 2026-03-25 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for guest orders', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_address',
            field=models.TextField(blank=True, help_text='Address for guest orders', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for guest orders', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for guest orders', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who placed the order (null for guest orders)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
