# Generated by Django 6.0.3 on 2026-03-24 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(help_text='Review this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.productreview'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(help_text='Review being voted on', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.productreview'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(help_text='User who voted', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', '-created_at'], name='product_rev_product_b958dd_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user'], name='product_rev_user_id_f1d802_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together={('review', 'user')},
        ),
    ]
