# Generated by Django 6.0.3 on 2026-03-24 15:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('wallet', 'E-Wallet'), ('cod', 'Cash on Delivery')], help_text='Payment method used', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Payment Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', help_text='Current payment status', max_length=20)),
                ('transaction_id', models.CharField(help_text='Unique transaction ID from payment gateway', max_length=200, unique=True)),
                ('reference_id', models.CharField(blank=True, help_text='Reference ID from payment gateway', max_length=200, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Complete response from payment gateway')),
                ('error_message', models.TextField(blank=True, help_text='Error message if payment failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Coupon description', max_length=200, null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('free_shipping', 'Free Shipping')], help_text='Type of discount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount amount or percentage', max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Minimum order amount required', max_digits=10)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=10, null=True)),
                ('usage_limit', models.IntegerField(blank=True, help_text='Total number of times coupon can be used', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('usage_limit_per_user', models.IntegerField(default=1, help_text='Number of times each user can use this coupon')),
                ('applicable_categories', models.TextField(blank=True, help_text='Comma-separated list of category IDs (leave empty for all)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Coupon is active and can be used')),
                ('start_date', models.DateTimeField(help_text='Coupon valid from')),
                ('end_date', models.DateTimeField(help_text='Coupon valid until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='coupons_code_94ae53_idx'), models.Index(fields=['is_active'], name='coupons_is_acti_dbb3f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Discount amount applied', max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(help_text='Coupon used', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.coupon')),
                ('order', models.ForeignKey(blank=True, help_text='Order this coupon was used for', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'coupon_usages',
            },
        ),
    ]
