# Generated by Django 6.0.3 on 2026-03-24 15:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly brand name', unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Brand logo', null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True, help_text='Brand description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly category name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Category cover image', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='Show this category on frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent category (for subcategories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name/title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly product name', unique=True)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('short_description', models.CharField(blank=True, help_text='Short description for product listings', max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Original product price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_percentage', models.IntegerField(default=0, help_text='Discount percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price after discount', max_digits=10, null=True)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Number of items in stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(help_text='Unique stock keeping unit', max_length=100, unique=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average customer rating', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('reviews_count', models.IntegerField(default=0, help_text='Total number of reviews')),
                ('featured_image', models.ImageField(help_text='Main product image', upload_to='products/featured/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage featured section')),
                ('is_active', models.BooleanField(default=True, help_text='Product is available for purchase')),
                ('seo_title', models.CharField(blank=True, help_text='SEO title for search engines', max_length=200, null=True)),
                ('seo_description', models.CharField(blank=True, help_text='SEO description for search engines', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Product brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Attribute name', max_length=100)),
                ('value', models.CharField(help_text='Attribute value', max_length=100)),
                ('product', models.ForeignKey(help_text='Product this attribute belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product')),
            ],
            options={
                'db_table': 'product_attributes',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product gallery image', upload_to='products/gallery/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
                'db_table': 'product_images',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_categor_9e60b3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_brand_i_0d1950_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_created_a77fb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'name', 'value')},
        ),
    ]
