# Generated by Django 6.0.3 on 2026-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_deleted_at_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(default=0, help_text='Total number of reviews'),
        ),
    ]
