# Generated by Django 6.0.3 on 2026-03-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_reviews_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/featured/'),
        ),
    ]
